braincrafted_bootstrap:
#    output_dir: ~
#    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
#    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
    less_filter: none # "less", "lessphp" or "none"
    auto_configure:
        assetic: true
        twig: true
#        knp_menu: true
#        knp_paginator: true
#    customize_variables:
#        variables_file: ~
#        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
#        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
