app_admin_purchase:
    resource: "@AppAdminPurchaseBundle/Controller/"
    type:     annotation
    prefix:   /

app_order:
    resource: "@AppOrderBundle/Controller/"
    type:     annotation
    prefix:   /

app_admin_product:
    resource: "@AppAdminProductBundle/Controller/"
    type:     annotation
    prefix:   /

app_product:
    resource: "@AppProductBundle/Controller/"
    type:     annotation
    prefix:   /

app_app:
    resource: "@AppAppBundle/Controller/"
    type:     annotation
    prefix:   /

app_admin_category:
    resource: "@AppAdminCategoryBundle/Controller/"
    type:     annotation
    prefix:   /

app_category:
    resource: "@AppCategoryBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine
