security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:           ^/admin
            form_login:
                provider:        fos_userbundle
                csrf_provider:   form.csrf_provider
                login_path:      admin_login
                check_path:      admin_login_check
            logout:
                path:          /admin/logout
                target:        /admin
            anonymous:         true

    access_control:
        - { path: ^/admin/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register,  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/,          role: ROLE_ADMIN }
